<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0"><channel><title>RabbitMQ - 标签 - Spaceack's Blog</title><link>https://spaceack.github.io/tags/rabbitmq/</link><description>RabbitMQ - 标签 - Spaceack's Blog</description><generator>Hugo -- gohugo.io</generator><language>zh-CN</language><managingEditor>spaceack@qq.com (Spaceack)</managingEditor><webMaster>spaceack@qq.com (Spaceack)</webMaster><copyright>This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.</copyright><lastBuildDate>Fri, 27 Aug 2021 07:28:48 +0000</lastBuildDate><atom:link href="https://spaceack.github.io/tags/rabbitmq/" rel="self" type="application/rss+xml"/><item><title>RabbitMQ pika错误处理 delivery acknowledgement on channel 1 timed out</title><link>https://spaceack.github.io/20210827-rabbitmq-pika%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86/</link><pubDate>Fri, 27 Aug 2021 07:28:48 +0000</pubDate><author>Spaceack</author><guid>https://spaceack.github.io/20210827-rabbitmq-pika%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86/</guid><description>AMQPChannelError 异常捕获信息： (406, 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more') 其他人也与到过这个问题 按照官方文档配置超时参数后问题解决。 pika.ConnectionParameters(heartbeat=600, blocked_connection_timeout=300) DOC: heartbeat_and_blocked_timeouts</description></item></channel></rss>